version: '3.9'

services:
  # ──────────────────────────── MySQL ────────────────────────────
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3307:3306"                       # hôte 3307 → conteneur 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:      ${DB_NAME:-mydb}
      MYSQL_USER:          ${DB_USER:-myuser}
      MYSQL_PASSWORD:      ${DB_PASSWORD:-mypassword}
    volumes:
      - db-data:/var/lib/mysql
      - ./backend/db_init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./backend/db_seed.sh:/docker-entrypoint-initdb.d/02-seed.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ──────────────────────────── Adminer ──────────────────────────
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8084:8080"
    depends_on:
      - mysql

  # ──────────────────────────── Backend (Flask) ──────────────────
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-mydb}
      DB_USER: ${DB_USER:-myuser}
      DB_PASSWORD: ${DB_PASSWORD:-mypassword}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-PvdrTAzTeR247sDnAZBr}
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:5000"                       # port exposé ; accès via http://localhost:5000
    # ⬅︎  plus de "command:" ici → on laisse le CMD du Dockerfile lancer Gunicorn

  # ──────────────────────────── Frontend (React) ─────────────────
  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL:        http://localhost:5000           # l’UI appelle directement l’API hôte
      REACT_APP_ADMIN_PASSWORD: ${ADMIN_PASSWORD:-PvdrTAzTeR247sDnAZBr}
    depends_on:
      - backend
    ports:
      - "3003:3000"                      # http://localhost:3003
    command: ["npm", "start"]

volumes:
  db-data:
