version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/app/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - '8080:8080'

  backend:
    build: ./backend
    container_name: python-backend
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
    depends_on:
      - mysql
    ports:
      - '5000:5000'

  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - backend
    ports:
      - '3000:3000'

volumes:
  db_data: