name: CI Backend

on: [push, pull_request]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/backend   
      
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
          MYSQL_USER: test
          MYSQL_PASSWORD: testpass
        ports:
          - "3306:3306"
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot --silent"
          --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Wait for MySQL
        run: |
          for i in {1..12}; do
            mysqladmin ping -h127.0.0.1 -uroot -proot && break
            sleep 5
          done

      - name: Run tests
        working-directory: backend
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: mydb
          DB_USER: test
          DB_PASSWORD: testpass
        run: pytest --cov=app
